CREATE TABLE esbuser.api_registry (
                                      id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                      app_code VARCHAR2(20) NOT NULL,
                                      app_name VARCHAR2(50) NOT NULL,
                                      creation_date DATE NOT NULL,
                                      created_by VARCHAR2(30) NOT NULL,
                                      approval VARCHAR2(50) NOT NULL,
                                      approve_by VARCHAR2(50),
                                      last_modify_by VARCHAR2(50),
                                      last_modify_date DATE,
                                      disabled VARCHAR2(5) CHECK (disabled IN ('true', 'false')),
                                      CONSTRAINT pk_api_registry PRIMARY KEY (app_code)

);

CREATE UNIQUE INDEX apiregidx1 ON esbuser.api_registry(app_code);



CREATE TABLE esbuser.its_switch_registry (
                                             id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                             switch_code VARCHAR(20) NOT NULL,
                                             switch_name VARCHAR(50) NOT NULL,
                                             creation_date DATE NOT NULL,
                                             created_by VARCHAR(30) NOT NULL,
                                             approval VARCHAR2(50) NOT NULL,
                                             approve_by VARCHAR2(50),
                                             last_modify_by VARCHAR2(50),
                                             last_modify_date DATE,
                                             disabled VARCHAR2(5) CHECK (disabled IN ('true', 'false')),
                                             CONSTRAINT pk_its_switch_registry PRIMARY KEY (switch_code)
);

CREATE UNIQUE INDEX itsswchregidx1 ON esbuser.its_switch_registry(switch_code);



CREATE TABLE esbuser.its_crypto_config (
                                           id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                           app_code VARCHAR(20) NOT NULL,
                                           switch_code VARCHAR(20) NOT NULL,
                                           its_private_keyfile VARCHAR(50) NOT NULL,
                                           its_public_keyfile VARCHAR(50) NOT NULL,
                                           switch_public_keyfile VARCHAR(50) NOT NULL,
                                           creation_date DATE NOT NULL,
                                           created_by VARCHAR(30) NOT NULL,
                                           approval VARCHAR2(50) NOT NULL,
                                           approve_by VARCHAR2(50),
                                           last_modify_by VARCHAR2(50),
                                           last_modify_date DATE,
                                           disabled VARCHAR2(5) CHECK (disabled IN ('true', 'false')),
                                           CONSTRAINT pk_its_crypto_config PRIMARY KEY (app_code, switch_code)
);

CREATE UNIQUE INDEX itscrptcfgidx1 ON esbuser.its_crypto_config(app_code, switch_code);

--
CREATE TABLE esbuser.its_3party_api_config (
                                               id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                               app_code VARCHAR(20) NOT NULL,
                                               switch_code VARCHAR(20) NOT NULL,
                                               tsq_url VARCHAR(50) NOT NULL,
                                               trf_url VARCHAR(50) NOT NULL,
                                               creation_date DATE NOT NULL,
                                               created_by VARCHAR(30) NOT NULL,
                                               approval VARCHAR2(50) NOT NULL,
                                               approve_by VARCHAR2(50),
                                               last_modify_by VARCHAR2(50),
                                               last_modify_date DATE,
                                               disabled VARCHAR2(5) CHECK (disabled IN ('true', 'false')),
                                               CONSTRAINT pk_its_3party_api_config PRIMARY KEY (id)
);

CREATE UNIQUE INDEX its3partyapicfgidx1 ON esbuser.its_3party_api_config(app_code, switch_code);


CREATE TABLE esbuser.its_3rdparty_addr (
                                                  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                                  app_code VARCHAR(20) NOT NULL,
                                                  switch_code VARCHAR(20) NOT NULL,
                                                  ip_addr VARCHAR(50) NOT NULL,
                                                  creation_date DATE NOT NULL,
                                                  created_by VARCHAR(30) NOT NULL,
                                                  approval VARCHAR2(50) NOT NULL,
                                                  approve_by VARCHAR2(50),
                                                  last_modify_by VARCHAR2(50),
                                                  last_modify_date DATE,
                                                  disabled VARCHAR2(5) CHECK (disabled IN ('true', 'false')),
                                                  CONSTRAINT pk_its_3party_addr PRIMARY KEY (id)
);

CREATE UNIQUE INDEX its3partyaddridx1 ON esbuser.its_3rdparty_addr(app_code, switch_code);




CREATE TABLE esbuser.audit_log (
                                   audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   table_name VARCHAR2(50) NOT NULL,
                                   operation VARCHAR2(10) NOT NULL,  -- 'INSERT', 'UPDATE', 'DELETE
                                   operation_date Date NOT NULL,
                                   operated_by VARCHAR2(30) NOT NULL,
                                   old_value CLOB,
                                   new_value CLOB
);

--
