CREATE TABLE esbuser.bck_roles
(
    id           int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    role_name    varchar(255) DEFAULT NULL,
    date_created timestamp    DEFAULT NULL,
    created_by   varchar(255) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE esbuser.bck_rev_users
(
    id              int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    firstname       varchar(40)  DEFAULT NULL,
    lastname        varchar(40)  DEFAULT NULL,
    email           varchar(50) NOT NULL,
    role_id         int          DEFAULT NULL,
    date_created    timestamp    DEFAULT NULL,
    date_modified   timestamp    DEFAULT NULL,
    last_login_date timestamp    DEFAULT NULL,
    login_ip        varchar(30)  DEFAULT NULL,
    modified_by     varchar(255) DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_email UNIQUE (email),
    CONSTRAINT rev_users_ibfk_1 FOREIGN KEY (role_id) REFERENCES esbuser.bck_roles (id)
);

CREATE TABLE esbuser.bck_permissions
(
    id              int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    permission_name varchar(255) DEFAULT NULL,
    uuid            varchar(255) DEFAULT NULL,
    date_created    timestamp    DEFAULT NULL,
    created_by      varchar(255) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE esbuser.bck_role_permission
(
    id            int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    role_id       int NOT NULL,
    permission_id int NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (permission_id) REFERENCES esbuser.bck_permissions (id),
    FOREIGN KEY (role_id) REFERENCES esbuser.bck_roles (id)
);

CREATE TABLE esbuser.channel_audit
(
    id                int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APPL_CODE         varchar(20) DEFAULT NULL,
    APPL_NAME         varchar(20) DEFAULT NULL,
    ENTRY_DATE        timestamp,
    ENTERED_BY        varchar(40) DEFAULT NULL,
    AUTH_FLG          varchar(2)  DEFAULT 'Y',
    AUTH_DATE         timestamp   DEFAULT NULL,
    AUTH_BY           varchar(40) DEFAULT NULL,
    VENDING_AGGR_CODE varchar(20),
    LAST_SWITCH_DATE  TIMESTAMP,
    FAILURE_THRESHOLD INT         DEFAULT 10,
    NUMBER_OF_MINUTES INT         DEFAULT 10,
    DATA_AGGR_CODE    VARCHAR(20) DEFAULT NULL,
    DEL_FLG           VARCHAR(2)  DEFAULT 'N',
    DEL_DATE          TIMESTAMP   DEFAULT sysdate,
    DEL_BY            VARCHAR(40) DEFAULT NULL,
    ACTION            VARCHAR(40) NOT NULL,
    ACTION_ID         VARCHAR(40) NOT NULL

);

CREATE TABLE esbuser.channel_aux
(
    id                int GENERATED BY DEFAULT ON NULL AS IDENTITY,
    APPL_CODE         varchar(20) DEFAULT NULL,
    APPL_NAME         varchar(20) DEFAULT NULL,
    ENTRY_DATE        timestamp,
    ENTERED_BY        varchar(40) DEFAULT NULL,
    AUTH_FLG          varchar(2)  DEFAULT 'Y',
    AUTH_DATE         timestamp   DEFAULT NULL,
    AUTH_BY           varchar(40) DEFAULT NULL,
    VENDING_AGGR_CODE varchar(20),
    LAST_SWITCH_DATE  TIMESTAMP,
    FAILURE_THRESHOLD INT         DEFAULT 10,
    NUMBER_OF_MINUTES INT         DEFAULT 10,
    DATA_AGGR_CODE    VARCHAR(20) DEFAULT NULL,
    DEL_FLG           VARCHAR(2)  DEFAULT 'N',
    DEL_DATE          TIMESTAMP   DEFAULT sysdate,
    DEL_BY            VARCHAR(40) DEFAULT NULL,
    DEACTIVATION_FLG  varchar(2) NOT NULL,
    APPROVAL_FLG      varchar(2) NOT NULL,


)
CREATE TABLE esbuser.app_audit
(
    id int GENERATED BY DEFAULT ON NULL AS IDENTITY,

)

CREATE TABLE esbuser.aggregator_audit
(
    id int GENERATED BY DEFAULT ON NULL AS IDENTITY,

) ;
    
INSERT INTO esbuser.bck_roles (role_name, date_created, created_by, app_code)
VALUES ('GUEST', sysdate, 'system', 'SWITCH');
INSERT INTO esbuser.bck_roles (role_name, date_created, created_by, app_code)
VALUES ('INITIATOR', sysdate, 'system', 'SWITCH');
INSERT INTO esbuser.bck_roles (role_name, date_created, created_by, app_code)
VALUES ('APPROVER', sysdate, 'system', 'SWITCH');
INSERT INTO esbuser.bck_roles (role_name, date_created, created_by, app_code)
VALUES ('ADMIN', sysdate, 'system', 'SWITCH');

INSERT INTO esbuser.bck_permissions (id, permission_name, uuid, date_created, created_by)
VALUES ('READ', NULL, sysdate, 'system');
INSERT INTO esbuser.bck_permissions (permission_name, uuid, date_created, created_by)
VALUES ('INITIATE_REQUEST', NULL, sysdate, 'system');
INSERT INTO esbuser.bck_permissions (permission_name, uuid, date_created, created_by)
VALUES ('APPROVE_SUBS', NULL, sysdate, 'system');
INSERT INTO esbuser.bck_permissions (permission_name, uuid, date_created, created_by)
VALUES ('CREATE_SUBS', NULL, sysdate, 'system');
INSERT INTO esbuser.bck_permissions (permission_name, uuid, date_created, created_by)
VALUES ('CREATE_USER', NULL, sysdate, 'system');



                                                                                                    
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (9, 1, 1);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (10, 2, 1);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (11, 3, 1);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (12, 4, 1);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (13, 2, 2);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (14, 3, 2);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (15, 4, 2);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (16, 3, 3);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (17, 4, 3);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (18, 2, 4);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (19, 3, 4);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (20, 4, 4);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (21, 4, 5);

INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (9, 1, 1);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (10, 5, 1);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (11, 6, 1);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (12, 7, 1);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (13, 5, 2);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (14, 6, 2);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (15, 7, 2);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (16, 6, 3);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (17, 7, 3);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (18, 5, 4);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (19, 6, 4);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (20, 7, 4);
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id)
VALUES (21, 7, 5);

UPDATE esbuser.bck_roles
SET id = 1
where id = 5;
UPDATE esbuser.bck_roles
SET id = 2
where id = 6;
UPDATE esbuser.bck_roles
SET id = 3
where id = 7;
UPDATE esbuser.bck_roles
SET id = 4
where id = 8;

create table esbuser.switch_resources
(
    id     number generated by default on null as identity,
    method varchar2(10),
    url    varchar2(75),
    constraint unq_swtch_resc UNIQUE (method, url)
);
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (14, 'GET', '/switch/getusers', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (15, 'GET', '/switch/getroles', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (16, 'POST', '/switch/updateuserrole', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (17, 'GET', '/switch/switch', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (18, 'POST', '/switch/switch', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (19, 'PUT', '/switch/switch', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (20, 'POST', '/switch/approve-switch', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (21, 'GET', '/switch/endpoint', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (22, 'POST', '/switch/endpoint', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (23, 'PUT', '/switch/endpoint', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (24, 'POST', '/switch/approve-endpoint', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (25, 'GET', '/switch/perf-stat', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (26, 'GET', '/switch/transactions', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (27, 'GET', '/switch/uploadfile', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (28, 'POST', '/switch/uploadfile', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (29, 'PUT', '/switch/uploadfile', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (30, 'POST', '/switch/uploadfile/approve', 'SWITCH');


create table esbuser.switch_permission_resources
(
    id            number generated by default on null as identity,
    permission_id number,
    resources_id  number,
    constraint unq_swtch_perm_resc UNIQUE (permission_id, resources_id)
);

INSERT INTO esbuser.bck_permissions (id, permission_name, uuid, date_created, created_by, app_code)
VALUES (5, 'READ', NULL, sysdate, 'system', 'SWITCH' );
INSERT INTO esbuser.bck_permissions (id, permission_name, uuid, date_created, created_by, app_code)
VALUES (6, 'CREATE', NULL, sysdate, 'system', 'SWITCH' );
INSERT INTO esbuser.bck_permissions (id, permission_name, uuid, date_created, created_by, app_code)
VALUES (7, 'APPROVE', NULL, sysdate, 'system', 'SWITCH' );
INSERT INTO esbuser.bck_permissions (id, permission_name, uuid, date_created, created_by, app_code)
VALUES (8, 'MODIFY-USERS', NULL, sysdate, 'system', 'SWITCH' );


INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (14, 14, 8, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (15, 15, 8, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (16, 16, 8, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (17, 17, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (18, 18, 6, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (19, 19, 6, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (20, 20, 7, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (21, 21, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (22, 22, 6, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (23, 23, 6, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (24, 24, 7, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (25, 25, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (26, 26, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (27, 27, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (28, 28, 6, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (29, 29, 6, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (30, 30, 6, 'SWITCH');


INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (11, 5, 5, 'SWITCH');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (12, 6, 5, 'SWITCH');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (13, 7, 5, 'SWITCH');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (14, 8, 5, 'SWITCH');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (15, 6, 6, 'SWITCH');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (16, 7, 6, 'SWITCH');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (17, 8, 6, 'SWITCH');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (18, 7, 7, 'SWITCH');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (19, 8, 7, 'SWITCH');
INSERT INTO esbuser.bck_role_permission (id, role_id, permission_id, app_code)
VALUES (20, 8, 8, 'SWITCH');

INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (31, 'GET', '/switch/auditLog', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (32, 'GET', '/switch/apiRegistry', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (33, 'POST', '/switch/apiRegistry/create', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (34, 'PUT', '/switch/apiRegistry/update' , 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (35, 'PUT', '/switch/apiRegistry/approval' , 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (36, 'PUT', '/switch/apiRegistry/enable_disable', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (37, 'POST', '/switch/switchregistry/create' , 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (38, 'PUT', '/switch/switchregistry/update' , 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (39, 'PUT', '/switch/switchregistry/approval', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (40, 'PUT', '/switch/switchregistry/enable_disable', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (41, 'GET', '/switch/switchregistry', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (42, 'GET', '/switch/crypto_config', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (43, 'POST', '/switch/crypto_config/create', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (44, 'PUT', '/switch/crypto_config/update', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (45, 'PUT', '/switch/crypto_config/approval', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (46, 'PUT', '/switch/crypto_config/enable_disable', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (47, 'DELETE', '/switch/crypto_config', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (48, 'POST', '/switch/thirdPartyAddr/create', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (49, 'PUT', '/switch/thirdPartyAddr/update', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (50, 'PUT', '/switch/thirdPartyAddr/approval' , 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (51, 'PUT', '/switch/thirdPartyAddr/enable_disable' , 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (52, 'DELETE', '/switch/thirdPartyAddr' , 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (53, 'GET', '/switch/thirdPartyAddr', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (54, 'POST', '/switch/apiConfig/create', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (55, 'PUT', '/switch/apiConfig/update', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (56, 'PUT', '/switch/apiConfig/approval', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (57, 'PUT', '/switch/apiConfig/enable_disable', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (58, 'DELETE', '/switch/apiConfig' , 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (59, 'GET', '/switch/apiConfig', 'SWITCH');


INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (60, 'GET', '/switch/apiRegistry/get_approved', 'SWITCH');
INSERT INTO esbuser.switch_resources(id, method, url, app_code)
values (60, 'GET', '/switch/apiRegistry/get_pending', 'SWITCH');

INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (31, 31, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (32, 32, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (33, 33, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (34, 34, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (35, 35, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (36, 36, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (37, 37, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (38, 38, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (39, 39, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (40, 40, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (41, 41, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (42, 42, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (43, 43, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (44, 44, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (45, 45, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (46, 46, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (47, 47, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (48, 48, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (49, 49, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (50, 50, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (51, 51, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (52, 52, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (53, 53, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (54, 54, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (55, 55, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (56, 56, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (57, 57, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (58, 58, 5, 'SWITCH');
INSERT INTO esbuser.switch_permission_resources(id, resources_id, permission_id, app_code)
values (59, 59, 5, 'SWITCH');

CREATE TABLE SWITCH_DELETION_ARCHIVE
(
    ID       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    MODULE   VARCHAR2(15),
    DEL_ID   NUMBER,
    DEL_DATE TIMESTAMP,
    DEL_BY   VARCHAR2(50),
    DATA     CLOB,
    PRIMARY KEY (ID)
);


