http.port=9897
https.port=9043
service.context=switch
key.alias=secure
keystore.password=v5p3LqRTJUqZwJ9sUIHK9g==
max.threads=1000
username=010113
transpt.scheme=http
localdb.jdbc.username=esbuser
localdb.jdbc.pwd=PRzcl3qsstXgQ0hRZooFCw==
localdb.jndi.context=jdbc/LocalDB
localdb.jdbc.driver.class=oracle.jdbc.OracleDriver
#localdb.jdbc.url=jdbc:oracle:thin:@localhost:1521/ORCL
localdb.jdbc.url=jdbc:oracle:thin:@infometics-testdb.c9i8226qisrt.eu-north-1.rds.amazonaws.com:1521/DATABASE
localdb.jdbc.validationQuery="select 1"
localdb.jdbc.removeAbandonedTimeout=60
localdb.jdbc.testWhileIdle=true
localdb.jdbc.timeBetweenEvictionRunsMillis=300000
app.token.expiration=3600000
refresh-token-time=900000
auth-token-time=30000000000