package constants;

public enum AppModules {

    AGGREGATOR, CHANNEL, AGGREGATOR_RESP_MAP, DATA_PRODUCT, SEQUENCE_TABLE, TIME_TABLE, TRANSACTION_ROUTE, ACCOUNT_CONFIG, SERVICE_PROVIDER, TRANSACTION_MANAGEMENT;
}
